baseURL: "linus-holmberg.github.io"
title: Linus Holmberg
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

#social:
#  twitter: LinusHolmberg

taxonomies:
  tag: tags

menu:
  main:
    - name: Home
      url: /
      weight: 1
    - name: More About Me
      url: /moreaboutme/
      weight: 2
    #- name: Projects
    #  url: /projects/
    #  weight: 3
    - name: Research
      url: /papers/
      weight: 4
    - name: Teaching
      url: /courses/
      weight: 5
    - name: News
      url: /news/
      weight: 6
    - name: CV
      url: /cv.pdf
      weight: 7

params:
  description: "Hi, I'm a <b>[Ph.D. student in Cognitive Science</b> at Linköping University (LiU)](https://liu.se/medarbetare/linho07), and employed as a [Ph.D. researcher at Jönköping University (JU)](https://ju.se/en/personinfo?sign=HOLLIN).
     <br><br>
    
     Broadly speaking, my research interest lies in making AI systems useful and understandable to all users. 
     One could say that my primary focus is in the intersection of Human-AI/Computer Interaction and Explainable AI, and that I use insights from cognitive science to inform my research.
     I do this under the supervision of <b>[Prof. Tom Ziemke](https://www.ziemke.se/)</b> (LiU), <b>[Prof. Maria Riveiro](https://ju.se/en/personinfo?sign=RIVMAR)</b> (JU), and <b>[Assoc. Prof. Serge Thill](https://www.ru.nl/en/people/thill-s)</b> (Donders Institue).

     <br><br>
     I obtained my first <b>MA in [Cognition & Communication](https://www.ku.dk/studies/masters/cognition-and-communication)</b> from the University of Copenhagen. 
     After that I studied a <b>MSc in [Data Science</b> at the University of Gothenburg](https://www.gu.se/en/study-gothenburg/data-science-big-data), while simutaniously working as an <b>associate researcher</b> in a sleep research project at the University of Gothenburg.
     I received my <b>BSc in [Cognitive Science](https://www.gu.se/studera/hitta-utbildning/kandidatprogram-i-kognitionsvetenskap-n1kog)</b> at the University of Gothenburg. 

     <br> <br>

     <b>Get in touch!</b> If you are interested in my reseach or work on something similar, please reach out!
     <br>
     I always appriciate an interesting discussion.
     "
  author: Linus Holmberg
  # googleAnalyticsID: ""
  DateFormat: "January 2006"
  defaultTheme: light
  hideFooter: true
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: false
  disableSpecial1stPost: true
  disableAnchoredHeadings: true
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: false
  ShowToc: false
  disableScrollToTop: true
  TocOpen: true
  ShowWordCount: false
  UseHugoToc: true
  comments: false
  math: true
  profileMode:
    enabled: true
    title: Linus Holmberg
    subtitle: "Hi, I'm a <b>[Ph.D. student in Cognitive Science</b> at Linköping University (LiU)](https://liu.se/medarbetare/linho07), and employed as a [Ph.D. researcher at Jönköping University (JU)](https://ju.se/en/personinfo?sign=HOLLIN).
     <br><br>
    
     Broadly speaking, my research interest lies in making AI systems useful and understandable to all users. 
     One could say that my primary focus is in the intersection of Human-AI/Computer Interaction and Explainable AI, and that I use insights from cognitive science to inform my research.
     I do this under the supervision of <b>[Prof. Tom Ziemke](https://www.ziemke.se/)</b> (LiU), <b>[Prof. Maria Riveiro](https://ju.se/en/personinfo?sign=RIVMAR)</b> (JU), and <b>[Assoc. Prof. Serge Thill](https://www.ru.nl/en/people/thill-s)</b> (Donders Institue).

     <br><br>
     I obtained my first <b>MA in [Cognition & Communication](https://www.ku.dk/studies/masters/cognition-and-communication)</b> from the University of Copenhagen. 
     After that I studied a <b>MSc in [Data Science</b> at the University of Gothenburg](https://www.gu.se/en/study-gothenburg/data-science-big-data), while simutaniously working as an <b>associate researcher</b> in a sleep research project at the University of Gothenburg.
     I received my <b>BSc in [Cognitive Science](https://www.gu.se/studera/hitta-utbildning/kandidatprogram-i-kognitionsvetenskap-n1kog)</b> at the University of Gothenburg. 

     <br> <br>

     <b>Get in touch!</b> If you are interested in my reseach or work on something similar, please reach out!
     <br>
     I always appriciate an interesting discussion.
     "
    imageUrl: "/picture.jpeg"
    imageWidth: 180
    imageHeight: 180
    imageTitle: Linus Holmberg
    buttons:

      - name: More About Me
        url: /moreaboutme/
      #- name: Projects
     #   url: /projects/
      - name: Research
        url: /papers/
      - name: Teaching
        url: /courses/
      - name: News
        url: /news/
      - name: CV
        url: /cv.pdf

  socialIcons:
    - name: CV
      url: "/cv.pdf"
    - name: LinkedIn
      url: "https://www.linkedin.com/in/linus-holmberg-2a7b5b239/"
    - name: Google Scholar
      url: "https://scholar.google.com/citations?user=QHS0iYQAAAAJ&hl"
    #- name: GitHub
    #  url: "https://github.com/linus-holmberg"
    - name: Email
      url: "mailto:linus.holmberg@ju.se"

  assets:
    disableHLJS: true
    disableScrollBarStyle: true
  cover:
    hiddenInList: true
    hiddenInSingle: true
  label:
    text: "Linus Holmberg"
    icon: /favicon.ico
    iconHeight: 18

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    guessSyntax: true
    style: autumn
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
